### PR TITLE
'octave' as persistent setting

### PR DESCRIPTION
**Pull request by ivy-rew**
allow to edit octave on non EN/UK compatible keyboards without modifying v2m.py -> https://github.com/svsdval/video2midi/discussions/19

### CODE REVIEW

**Review by svsdval — COMMENTED** [review]
looks fine ;) As variant maybe add new buttons near octave label into settings window to adjust the octave settings ?

**Comment by ivy-rew** [comment]
Yeah good idea @svsdval . I'll try to add such buttons.

**Comment by ivy-rew** [comment]
now we have the buttons too. I think both changes make sense ... if I change octave, I also need to store/load this setting. And having buttons on the UI ... makes key support less important.

**Comment by svsdval** [comment]
Changes looks fine, that's like in blender, where you have a buttons for most of functions and keys for fast call ;)

**Pull request merged**
