### PR TITLE
Refactor: config read write to own unit

### PR DESCRIPTION
**Pull request by ivy-rew**
Hi @svsdval 
I just stumbled over this project and absolutely love the intention and functionality of it. 
In order to learn more about how the featureset has been built, I suggest a minor refactoring here. If you are open to such changes, more similar improvements may follow... 

Any feedback of re-editing is welcome. I just tried to reduce the amount of code in the main unit to make it easier to digest for newcomers and also in the hope to make it unit-test ready.

### CODE REVIEW

**Comment by svsdval** [comment]
Looks like you made some errors while refactoring the code,if I try to load an old settings file saved in previous versions of this application, the application crashed with:

```
Traceback (most recent call last):
  File "/home/svsdval/projects/v2m/video2midi-refact-configReadWrite/./v2m.py", line 2098, in <module>
    main();
  File "/home/svsdval/projects/v2m/video2midi-refact-configReadWrite/./v2m.py", line 1902, in main
    loadsettings( settingsfile )
  File "/home/svsdval/projects/v2m/video2midi-refact-configReadWrite/./v2m.py", line 213, in loadsettings
    colorWindow_colorBtns_channel_labels[i].text = "Ch:" + str(prefs.keyp_colors_channel[i]+1);
IndexError: list index out of range

```
Therefore, it is necessary to fix and do additional testing before I accept the pull request.

Here is old settings file:
[YOU SPIN ME RIGHT ROUND (LIKE A RECORD) - Piano Tutorial-gv7NnkSWKFs.mkv.ini.txt](https://github.com/svsdval/video2midi/files/6796299/YOU.SPIN.ME.RIGHT.ROUND.LIKE.A.RECORD.-.Piano.Tutorial-gv7NnkSWKFs.mkv.ini.txt)

**Comment by ivy-rew** [comment]
Thanks a lot for your feedback @svsdval 

The issues is now addressed and the older versions should load as they did before. 

I'll think of a way to make this special case unit-testable so that we can cover this feature with a test. And never again someone will lightheartedly brake it again.

**Comment by ivy-rew** [comment]
Okay I think we got a good first solution that builds this project:
1. it verifies the v2m.py with python 3.7, 3.8 and 3.9
2. installs the dependencies outlined in requirements.txt
3. run the tests ... actually just one simple test of mine regarding settings load/save

an example can be seen here: https://github.com/ivy-rew/video2midi/actions ... and of course also in this repo as soon as this PR is on master.

**Comment by svsdval** [comment]
Ok, looks and works with my tests fine =)  Thanks for your work and for your time to this project  =) I accept your pull request =)

**Comment by ivy-rew** [comment]
Thanks a lot @svsdval . I love to contribute to this powerful door opener for my piano skills :+1:

**Pull request merged**
